name: Deploy the image to ECR for CLO835 Assignment1

on: 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Images for assignment2
    runs-on: ubuntu-latest

   
    steps:

    - name: code run
      uses: actions/checkout@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Building and pushing images to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: assignment1-ecr
        IMAGE_TAG: v0.1
      run: |
        cd clo835_summer2023_assignment1-main/
        ls -ltra
        # Build image for mysql db
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:db_$IMAGE_TAG -f Dockerfile_mysql .

        # Unit test for mysql container
        docker run -d --name my_db $ECR_REGISTRY/$ECR_REPOSITORY:db_$IMAGE_TAG
        docker ps
        echo "Pause for 10 seconds to let container start"
        sleep 10
        
        # Pushing the mysql db image to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:db_$IMAGE_TAG

        # Build image for application
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:app_$IMAGE_TAG -f Dockerfile .
        
        # Pushing the application image to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:app_$IMAGE_TAG

        
